@extends('_masterUsers')

@section('title')
    Developer's Best Friend
@stop

@section('bodyContent_1')
        This is the Random User Generator.  This tool will generate a number of fake users complete with birthdates and biographical sketches, if desired. 
@stop

@section('bodyContent_2')
     <!-- 1. Text box for a number 
             2. Two checkboxes
             3. Button to generate the users.
     -->
    <form action="{{ url('generateUsers') }}" method="POST">
        <div>
            <label for='numberOfUsers'>Please enter a number for how many users to generate.  Maximum value is allowed is 99.</label><br>
            <input type="text" maxlength=2 size=1 name='numberOfUsers' id='numberOfUsers' >
            <br>
            <br>
            <label for='includeBirthdate'>Include a Birthdate?</label><br>
            <input type='checkbox' name='includeBirthdate' id='includeBirthdate'>
            <br>
            <br>            
            <label for='includeProfile'>Include a Profile?</label><br>
            <input type='checkbox' name='includeProfile' id='includeProfile' value='1'>
            <br>
            <br>
            <input class="button" type='submit' value="Let's generate some People!">
        </div>
     </form>
@stop
@section('bodyContent_3')
    <?php 
        if(isset( $data['numberOfUsers'])){

            /* Validation - Produce a warning message when
             *      1. The value entered is not a number.
             *      2.  The value entered is a number, but not between 1 and 10. 
             */
            if (! is_numeric($data['numberOfUsers']) && $data['numberOfUsers']!= "" ) {
                echo "Please enter only a numeric value in the textbox.";
            } else {
                if( ! ($data['numberOfUsers'] > 0  && $data['numberOfUsers'] < 100 ) ) {
                    echo "Please enter only a numeric value between 1 and 99.";
                } else {
                    // Loop for the number of users needed.
                    for ($i = 1; $i <= $data['numberOfUsers']; $i++) {
                    /* Instantiate Faker.  Use coin toss to set the gender, this is important for Profile
                    generation later.  I know, i know, i should put this in its own method or class, but time is short
                      */
                        $faker = Faker\Factory::create();
                        $genderSelect = rand (0 , 1);
                        $gender = "";
                        if ($genderSelect) {
                            $gender = "female";         
                        } else {
                            $gender = "male";
                        }
                        // echo user details
                        $firstName = $faker->firstName($gender);
                        $lastName = $faker->lastName;
                        echo $firstName . " " . $lastName . "<br/>";
                        echo $faker->address."<br/>";
                        // Provide the birthdate if indicated in the UI 
	      if (isset($data['includeBirthdate'])) {
                           echo "Birthdate: ".$faker->date($format='m-d-Y')."<br/>";
	     }
                        /* Provide the profile if indicated in the UI
                        ProfileGenerator is a custom class i created.  Look in app/classes/ProfileGenerator.php
                        for the implementation.  The class needs first name, last name and gender (set above)
                        for the constructor.  All profile information is generated by this class.  This 
                        was fun code to write, and definitely has room for expansion. */
	     if (isset($data['includeProfile']) ) {
                           $profile = new ProfileGenerator($firstName, $lastName, $gender);
	         echo "Profile: ". $profile->getProfile() ."<br/>";
	     }
                        echo"<br/>";
                 }
            }
        }
     }
    ?>
@stop


